bled_rules: # rule identifiers to exclude from running
  - line_length
  # - trailing_newline
  # - trailing_whitespace
  # - colon
  # - control_statement
  # - file_length
  - force_cast
  - cyclomatic_complexity
  # - function_body_length
  # - leading_whitespace
  # - nesting
  # - operator_whitespace
  # - return_arrow_whitespace
  # - todo
  # - type_body_length
  # - type_name
  # - variable_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - DTMaster
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Frameworks
  - Libraries
  - DTMaster/Resources
# parameterized rules can be customized from this configuration file
line_length: 128
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 500 # warning
  - 800 # error
# parameterized rules are first parameterized as a warning level, then error level.
